// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// block_rar_opt
void block_rar_opt(int n_patients, int block_incr, float failure_cost, float block_cost, std::string sqlite_fname, float prior_a0, float prior_a1, float prior_b0, float prior_b1, std::string transition_dist, std::string transition_rwd, std::string terminal_reward);
RcppExport SEXP _blockRARopt_block_rar_opt(SEXP n_patientsSEXP, SEXP block_incrSEXP, SEXP failure_costSEXP, SEXP block_costSEXP, SEXP sqlite_fnameSEXP, SEXP prior_a0SEXP, SEXP prior_a1SEXP, SEXP prior_b0SEXP, SEXP prior_b1SEXP, SEXP transition_distSEXP, SEXP transition_rwdSEXP, SEXP terminal_rewardSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_patients(n_patientsSEXP);
    Rcpp::traits::input_parameter< int >::type block_incr(block_incrSEXP);
    Rcpp::traits::input_parameter< float >::type failure_cost(failure_costSEXP);
    Rcpp::traits::input_parameter< float >::type block_cost(block_costSEXP);
    Rcpp::traits::input_parameter< std::string >::type sqlite_fname(sqlite_fnameSEXP);
    Rcpp::traits::input_parameter< float >::type prior_a0(prior_a0SEXP);
    Rcpp::traits::input_parameter< float >::type prior_a1(prior_a1SEXP);
    Rcpp::traits::input_parameter< float >::type prior_b0(prior_b0SEXP);
    Rcpp::traits::input_parameter< float >::type prior_b1(prior_b1SEXP);
    Rcpp::traits::input_parameter< std::string >::type transition_dist(transition_distSEXP);
    Rcpp::traits::input_parameter< std::string >::type transition_rwd(transition_rwdSEXP);
    Rcpp::traits::input_parameter< std::string >::type terminal_reward(terminal_rewardSEXP);
    block_rar_opt(n_patients, block_incr, failure_cost, block_cost, sqlite_fname, prior_a0, prior_a1, prior_b0, prior_b1, transition_dist, transition_rwd, terminal_reward);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_blockRARopt_block_rar_opt", (DL_FUNC) &_blockRARopt_block_rar_opt, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_blockRARopt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
