# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

block_rar_opt <- function(n_patients, block_incr, error_cost, block_cost, sqlite_fname, prior_prob = 0.5, prior_strength = 1.0, test_stat = "wald") {
    invisible(.Call(`_blockRARopt_block_rar_opt`, n_patients, block_incr, error_cost, block_cost, sqlite_fname, prior_prob, prior_strength, test_stat))
}

