# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Use TrialMDP to compute an optimal trial design
#'
#' Given the number of patients, failure cost, and stage cost, compute an optimal trial design and save it to a SQLite database. 
#'
#' @param n_patients the number of patients in the trial
#' @param failure_cost parameter representing the cost of patient failures
#' @param block_cost parameter representing the cost of each additional trial stage
#' @param sqlite_fname output filepath for trial design SQLite database
#' @param min_size minimum size for a trial stage. Default=4
#' @param block_incr require trial stage sizes to be multiples of this number. Default=2
#' @param prior_a0 smoothing/pseudocount hyperparameter for computing transition probabilities. Default=1.0
#' @param prior_a1 smoothing/pseudocount hyperparameter for computing transition probabilities. Default=1.0
#' @param prior_b0 smoothing/pseudocount hyperparameter for computing transition probabilities. Default=1.0
#' @param prior_b1 smoothing/pseudocount hyperparameter for computing transition probabilities. Default=1.0
#' @param transition_dist name of transition probability distribution. Default="beta_binom". We do not recommend changing this.
#' @param test_statistic name of test statistic for which to optimize. Default="scaled_cmh". We do not recommend changing this.
#' @param act_l smallest allocation fraction to treatment A. i.e., Phi = {act_l, ..., act_u}. Default=0.2
#' @param act_u largest allocation fraction to treatment A. i.e., Phi = {act_l, ..., act_u}. Default=0.8
#' @param act_n number of possible allocation fractions, uniformly spaced. i.e., |Phi| = act_n. Default=7
#'
#' @return None. Trial design is written to disk.
trial_mdp <- function(n_patients, failure_cost, block_cost, sqlite_fname, min_size = 4L, block_incr = 2L, prior_a0 = 1.0, prior_a1 = 1.0, prior_b0 = 1.0, prior_b1 = 1.0, transition_dist = "beta_binom", test_statistic = "scaled_cmh", act_l = 0.2, act_u = 0.8, act_n = 7L) {
    invisible(.Call(`_TrialMDP_trial_mdp`, n_patients, failure_cost, block_cost, sqlite_fname, min_size, block_incr, prior_a0, prior_a1, prior_b0, prior_b1, transition_dist, test_statistic, act_l, act_u, act_n))
}

