
name: build_and_test

on: [push, pull_request]

jobs:
    build_package:
        name: build_package
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        steps: 
            - uses: actions/checkout@master
            - uses: r-lib/actions/setup-r@v1
              with:
                  r-version: '3.6.3'
            - run: Rscript -e 'install.packages("Rcpp"); install.packages("RSQLite")'
            - run: R CMD INSTALL .
 
    #run_script:
    #    name: run_script
    #    needs: build_package
    #    runs-on: [ubuntu-latest]
